# ==========================================================
# TuMags Reduction Pipeline Configuration (YAML)
# ==========================================================
# Example:
#   python3 ../../TuMags_Reduction_Pipeline/process_data_main.py \
#       -f ../../TuMags_Reduction_Pipeline/config_tumag.yaml
#
# IMPORTANT:
# - Parameter names must be unique (no duplicates across levels).
# - Boolean and None keywords are lowercase: false, true, none
# - results can be checked using python3 visor.py /Volumes/TuMag_d1/reduccion/.../file.fits
# ==========================================================


# ----------------------------------------------------------
# GLOBAL PARAMETERS
# ----------------------------------------------------------

obs_ID: "31_QSUN"                   # Observation ID 
proc_version: "0.4" # con cross-talk standard

# process_line: "2.02"              # Observation mode to process
process_line: "0p"              # Observation mode to process

# process_files: 2
process_ocs: ":"                  # ":" -> all, or range, or single ID
process_files: ":"                # ":" -> all, or range, or single ID

parallel: false
max_workers: 8 

tumag_data_location: "./"         # Path to Organized_files_local folder
# Organized_files_local_folder_name: "Organized_files_TuMag_d2"
Organized_files_local_folder_name: "Organized_files_TuMag_d4"

output_folder: "/Volumes/TuMag_d5/reduccion/"   # Output results folder


# ----------------------------------------------------------
# REPROCESSING OPTIONS
# ----------------------------------------------------------
force_redo:
  redo_flat: false                # Recalculate flats
  redo_dark: false                # Recalculate darks
  level0_5: true
  level0_6: false
  level0_7: true
  level1_0: true
  level1_1: false
  use_pd: false

# ----------------------------------------------------------
# PLOTTING OPTIONS
# ----------------------------------------------------------
plots:
  plot_darks: false
  plot_flats: false
  plot_level0_5: false
  plot_level0_6: false
  plot_level0_7: false
  plot_level1_0: true
  plot_level1_1: true
  roi_plots: [1, -1, 1, -1]


# ----------------------------------------------------------
# DARK AND FLAT OPTIONS
# ----------------------------------------------------------
darks_indexes:
  dark_from:
  dark_to: 

flat_norm_roi: [250, -250, 250, -250]  # sugerido por Fbailen (toda la imagen, pero sin mascara)
dark_file: false # npy with the dark (optinonal) 
flat_file: false # npy with the flat (optinonal)
import_blueshift_guess: True
norm_method: "blueshift"
remove_prefilter: True
pref_model: True
discard_repetitions: null # TBD
flat_optimization: true


# ----------------------------------------------------------
# LEVEL 0.5 OPTIONS
# ----------------------------------------------------------
level_05:
  filtering: true                 # Remove high-frequency content
  save_level_05: true             # Save processed level 0.5 data

size: 2016
centro: [973, 996]               # [size // 2 - 35, size // 2 - 12]
corte: 800


# ----------------------------------------------------------
# LEVEL 0.7 OPTIONS
# ----------------------------------------------------------
level_07:
  align_mode: "fourier"           # "fourier" or "destretch"
  align_sequence: 1          
  # "0" = Align modulations in both cams, then cam 1 w.r.t cam 0 (global ROI or quadrants)
  # "1" = Align cam 1 respect cam 0 first, then modulations. Assumes same jitter cam0 and 2. (global ROI or quadrants)
  # "2" = manual. Requires manual_shift
  align_roi: [100,1500,100,1500]
  align_accuracy: 0.001
  align_rot_data_filter: "alignment_results.csv"   # e.g. "pinholes_Fe2.02.csv" le cambio el nombre...
  align_quadrants: 0 #-8 #-16
  align_verbose: false
  align_modulations: false
  aligment_level: "dataset"
  advanced_alignment: true
  advanced_wave: 0 #[0,1,2,3,4,5,6,7,8,9] # '_av' todas las landas 
  advanced_save: true
  advanced_overwrite: true
  destretch_aling_cam: 'same'
  # 'all' = all images (2x4) simultaneously
  # 'full' = first cams then mods
  # 'same' = equivalent to align_sequence: 1 but using destretch
  destretch_n_iterations: 100
  destretch_ngrid: 4
  destretch_lr: 0.1
  destretch_lambda_tt: 0.02
  demod_matrix: 'demod_matrices_david_v2' #demod_matrices_acampos, demod_matrices, demod_matrices_david, demod_matrices_david_ct
  demod_mode: 'join' # 'join'
  add_level_07_label: '' #'dt'  special "av" para el uso de todas las landas
  manual_shift: [0.5, 0.02] # [shift_y, shift_x] to apply to cam2 (only if align_sequence == 2)

# ----------------------------------------------------------
# LEVEL 1.0 OPTIONS
# ----------------------------------------------------------
level_10:
  crosst_mode: "jaeggli"         # "jaeggli" or "standard"
  crosst_strategy: "sequential"   # "sequential" | "simultaneous"
  crosst_roi: [100,1500,100,1500]     # Normalization region
  crosst_region: [100,1500,100,1500] # Crosstalk calculation region
  crosst_threshold:  0.01 # Single (only V, or three array,list (for QUV independent))
  crosst_intensity_threshold: 0.8 # 0.01 thersshold for avoid umbra (intensity). 0 means not used
  crosst_last_wave: -3 #used -1 for standard and -2 for jaeggli
  crosst_quadrants: 0
  crosst_interference: 2 #"Iref2Q_polycoef_comm1_Fe2.02.csv" #8          # or 'comm1_cal.npz' file
  crosst_dual: false #8          # or 'comm1_cal.npz' file
  normalization: 0
  plot_crosst_method: false
  crosst_verbose: false
  add_level_10_label: '' #_inter8'

crosstalk:
  apply_only: false     # activa el modo "aplicar sin estimar"
  use_local: true      # usa derivadas (Ix,Iy[,L]) al aplicar
  local_order: 1       # 1 -> Ix,Iy; 2 -> + Laplaciano
  deriv_sigma: 0.0     # suavizado de I para derivadas
  # coeficientes globales por canal
  coeffs_global:
    Q: {a: -0.001489, b: -0.079376, c: 0.009570, d: 0.002892, e: 0.0}
    U: {a:  0.000223, b: 0.006636, c:  0.000642,     d: -0.002877,     e: 0.0}
    V: {a:  -0.000466, b: -0.000242,     c:  0.004103,     d: -0.008473,     e: 0.0}
  channels: ["Q","U","V"]

# ----------------------------------------------------------
# LEVEL 1.1 OPTIONS
# ----------------------------------------------------------
zernike_id: "06_SPOT_Mg1_0" #"06_SPOT_Fe2.02_0"

#----- DEBUGGING OPTIONS
debug:
  activate: false
  zoom_center: [600,600]
  zoom_size: 600
  filter_test: false
  allow_99: true


# ----------------------------------------------------------
# OBSERVATION MODES (REFERENCE)
# ----------------------------------------------------------
# observation_modes = {
#     0   : "0s",
#     1   : "0p",
#     2   : "1",
#     3   : "2.02",
#     4   : "2.06",
#     5   : "3.02",
#     6   : "3.06",
#     7   : "4",
#     8   : "5.02",
#     9   : "5.06",
#     64  : "PD_calibration",
#     65  : "Spectral_calibration",
#     66  : "Polarimetric_calibration",
#     128 : "Test"
# }

epsilon: 0.2
